version: '2'
services:
  local-varnish-cache:
    image: senizm/varnish:1.0.0
    container_name: local-varnish-cache
    environment:
      - VARNISH_BACKEND_HOST=127.0.0.1
      - VARNISH_BACKEND_PORT=8080
      - VARNISH_BACKEND_HOST2=localhost
      - VARNISH_BACKEND_PORT2=9090
      - VARNISH_BACKEND_TTL=30s
      - VARNISH_BACKEND_GRACE=15s
      - VARNISH_IMAGE_HOST=127.0.0.1
      - VARNISH_IMAGE_PORT=9091
      - VARNISH_IMAGE_TTL=3600s
      - VARNISH_PROFILE=dev
    ports:
      - "8085:8085"